package com.liucan.mapper;

import com.liucan.entity.Bookshelf;
import com.liucan.entity.BookshelfExample;

import java.util.HashMap;
import java.util.List;


import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface BookshelfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    long countByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer bookshelfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insert(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insertSelective(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    List<Bookshelf> selectByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    Bookshelf selectByPrimaryKey(Integer bookshelfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bookshelf record, @Param("example") BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExample(@Param("record") Bookshelf record, @Param("example") BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKey(Bookshelf record);


    List<Bookshelf> queryByLimit(HashMap<String,Object> map);

    int queryCount(HashMap<String,Object> map);

    void deletebookshelfs(@Param("bookshelfIds") Integer[] bookshelfIds);

    void deletebookshelf(Integer bookshelfId);

    Bookshelf querybookshelfById(Integer bookshelfid);

    void updatebookshelf(Bookshelf bookshelf);

    void addbookshelf(Bookshelf bookshelf);

    @Select("select * from bookshelf")
    List<Bookshelf> selectall();
}