package com.liucan.mapper;


import com.liucan.entity.Booktype;
import com.liucan.entity.BooktypeExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.omg.PortableInterceptor.INACTIVE;

public interface BooktypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    long countByExample(BooktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByExample(BooktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer booktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insert(Booktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insertSelective(Booktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    List<Booktype> selectByExample(BooktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    Booktype selectByPrimaryKey(Integer booktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Booktype record, @Param("example") BooktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExample(@Param("record") Booktype record, @Param("example") BooktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(Booktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKey(Booktype record);
    List<Booktype> queryByLimit(HashMap<String,Object> map);

    int queryCount(HashMap<String,Object> map);

    void deletebooktypes(@Param("booktypeIds") Integer[] booktypeIds);

    void deletebooktype(Integer booktypeId);

    Booktype querybooktypeById(Integer booktypeid);

    void updatebooktype(Booktype booktype);

    void addbooktype(Booktype booktype);


@Select("select * from booktype")
    List<Booktype> selectall();
}