package com.liucan.mapper;

import com.liucan.entity.Book;
import com.liucan.entity.BookExample;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    Book selectByPrimaryKey(Integer bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKey(Book record);
    @Update("update book set bookstatus=1 where bookid=#{bookid}")
    void updatebookstatus(Integer bookid);
     @Update("update book set bookstatus=0 , borrowtotals=borrowtotals+1 where bookid=#{bookid}")
    void updatestatus(Integer bookid);

    Book selectbybookid(Integer bookid);


    List<Book> queryByLimit(HashMap<String,Object> map);

    int queryCount(HashMap<String,Object> map);

    void deletebooks(@Param("bookIds") String[] bookIds);

    void deletebook(String bookId);

    Book querybookById(String bookid);

    void updatebook(Book book);

    void addbook(Book book);


}