package com.liucan.mapper;

import com.liucan.entity.Borrowecord;
import com.liucan.entity.BorrowecordExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    long countByExample(BorrowecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByExample(BorrowecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer borrowecordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insert(Borrowecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insertSelective(Borrowecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    List<Borrowecord> selectByExample(BorrowecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    Borrowecord selectByPrimaryKey(Integer borrowecordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Borrowecord record, @Param("example") BorrowecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExample(@Param("record") Borrowecord record, @Param("example") BorrowecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(Borrowecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrowecord
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKey(Borrowecord record);

    List<Borrowecord> queryByLimit(HashMap<String,Object> map);

    int queryCount(HashMap<String,Object> map);
}