package com.liucan.mapper;

import com.liucan.entity.Fine;
import com.liucan.entity.FineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    long countByExample(FineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByExample(FineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer fineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insert(Fine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insertSelective(Fine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    List<Fine> selectByExample(FineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    Fine selectByPrimaryKey(Integer fineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fine record, @Param("example") FineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExample(@Param("record") Fine record, @Param("example") FineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(Fine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKey(Fine record);

    void insertfine(Fine fine);
}