package com.liucan.mapper;

import com.liucan.entity.Reader;
import com.liucan.entity.ReaderExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    long countByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int deleteByPrimaryKey(String readid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insert(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int insertSelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    List<Reader> selectByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    Reader selectByPrimaryKey(String readid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByExample(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    int updateByPrimaryKey(Reader record);

    List<Reader> queryByLimit(HashMap<String,Object> map);

    int queryCount(HashMap<String,Object> map);

    void deletereaders(@Param("readerIds") String[] readerIds);

    void deletereader(String readerId);

    Reader queryreaderById(String readerid);

    void updatereader(Reader reader);

    void addreader(Reader reader);

    int countnow(String s);
}