package com.liucan.entity;

import java.util.ArrayList;
import java.util.List;

public class BookshelfExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public BookshelfExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookshelfidIsNull() {
            addCriterion("bookshelfid is null");
            return (Criteria) this;
        }

        public Criteria andBookshelfidIsNotNull() {
            addCriterion("bookshelfid is not null");
            return (Criteria) this;
        }

        public Criteria andBookshelfidEqualTo(Integer value) {
            addCriterion("bookshelfid =", value, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidNotEqualTo(Integer value) {
            addCriterion("bookshelfid <>", value, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidGreaterThan(Integer value) {
            addCriterion("bookshelfid >", value, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookshelfid >=", value, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidLessThan(Integer value) {
            addCriterion("bookshelfid <", value, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidLessThanOrEqualTo(Integer value) {
            addCriterion("bookshelfid <=", value, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidIn(List<Integer> values) {
            addCriterion("bookshelfid in", values, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidNotIn(List<Integer> values) {
            addCriterion("bookshelfid not in", values, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidBetween(Integer value1, Integer value2) {
            addCriterion("bookshelfid between", value1, value2, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfidNotBetween(Integer value1, Integer value2) {
            addCriterion("bookshelfid not between", value1, value2, "bookshelfid");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameIsNull() {
            addCriterion("bookshelfname is null");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameIsNotNull() {
            addCriterion("bookshelfname is not null");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameEqualTo(String value) {
            addCriterion("bookshelfname =", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameNotEqualTo(String value) {
            addCriterion("bookshelfname <>", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameGreaterThan(String value) {
            addCriterion("bookshelfname >", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameGreaterThanOrEqualTo(String value) {
            addCriterion("bookshelfname >=", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameLessThan(String value) {
            addCriterion("bookshelfname <", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameLessThanOrEqualTo(String value) {
            addCriterion("bookshelfname <=", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameLike(String value) {
            addCriterion("bookshelfname like", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameNotLike(String value) {
            addCriterion("bookshelfname not like", value, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameIn(List<String> values) {
            addCriterion("bookshelfname in", values, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameNotIn(List<String> values) {
            addCriterion("bookshelfname not in", values, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameBetween(String value1, String value2) {
            addCriterion("bookshelfname between", value1, value2, "bookshelfname");
            return (Criteria) this;
        }

        public Criteria andBookshelfnameNotBetween(String value1, String value2) {
            addCriterion("bookshelfname not between", value1, value2, "bookshelfname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookshelf
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 29 16:04:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}