package com.liucan.entity;

import org.springframework.format.annotation.DateTimeFormat;

import java.security.PublicKey;
import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish_id
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */

    private Integer bookid;
    private Integer booktypeid;
    private Integer bookshelfid;
    private String author;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date publishdate;
    private String content;
    private Date indate;
    private Integer bookstatus;
    private Integer borrowtotals;
    private String translator;
    private String publisher;
    private Booktype booktype;
    private Bookshelf bookshelf;

    public Booktype getBooktype() {
        return booktype;
    }

    public void setBooktype(Booktype booktype) {
        this.booktype = booktype;
    }

    public Bookshelf getBookshelf() {
        return bookshelf;
    }

    public void setBookshelf(Bookshelf bookshelf) {
        this.bookshelf = bookshelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn
     *
     * @return the value of book.isbn
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn
     *
     * @param isbn the value for book.isbn
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    public String getBookname() {
        return bookname;
    }

    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    public Integer getBookid() {
        return bookid;
    }

    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    public Integer getBooktypeid() {
        return booktypeid;
    }

    public void setBooktypeid(Integer booktypeid) {
        this.booktypeid = booktypeid;
    }

    public Integer getBookshelfid() {
        return bookshelfid;
    }

    public void setBookshelfid(Integer bookshelfid) {
        this.bookshelfid = bookshelfid;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Date getPublishdate() {
        return publishdate;
    }

    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getIndate() {
        return indate;
    }

    public void setIndate(Date indate) {
        this.indate = indate;
    }

    public Integer getBookstatus() {
        return bookstatus;
    }

    public void setBookstatus(Integer bookstatus) {
        this.bookstatus = bookstatus;
    }

    public Integer getBorrowtotals() {
        return borrowtotals;
    }

    public void setBorrowtotals(Integer borrowtotals) {
        this.borrowtotals = borrowtotals;
    }

    public String getTranslator() {
        return translator;
    }

    public void setTranslator(String translator) {
        this.translator = translator;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
}
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publish_id
     *
     * @return the value of book.publish_id
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
