package com.liucan.entity;

public class Booktype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.booktypeid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Integer booktypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktype.booktypename
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String booktypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.booktypeid
     *
     * @return the value of booktype.booktypeid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Integer getBooktypeid() {
        return booktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.booktypeid
     *
     * @param booktypeid the value for booktype.booktypeid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setBooktypeid(Integer booktypeid) {
        this.booktypeid = booktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktype.booktypename
     *
     * @return the value of booktype.booktypename
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getBooktypename() {
        return booktypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktype.booktypename
     *
     * @param booktypename the value for booktype.booktypename
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setBooktypename(String booktypename) {
        this.booktypename = booktypename == null ? null : booktypename.trim();
    }
}