package com.liucan.entity;

public class Bookshelf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.bookshelfid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Integer bookshelfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.bookshelfname
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String bookshelfname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.bookshelfid
     *
     * @return the value of bookshelf.bookshelfid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Integer getBookshelfid() {
        return bookshelfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.bookshelfid
     *
     * @param bookshelfid the value for bookshelf.bookshelfid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setBookshelfid(Integer bookshelfid) {
        this.bookshelfid = bookshelfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.bookshelfname
     *
     * @return the value of bookshelf.bookshelfname
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getBookshelfname() {
        return bookshelfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.bookshelfname
     *
     * @param bookshelfname the value for bookshelf.bookshelfname
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setBookshelfname(String bookshelfname) {
        this.bookshelfname = bookshelfname == null ? null : bookshelfname.trim();
    }
}