package com.liucan.entity;

public class BorrowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.bookid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.readerid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String readerid;

    public BorrowKey() {
    }

    public BorrowKey(Integer bookid, String readerid) {
        this.bookid = bookid;
        this.readerid = readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.bookid
     *
     * @return the value of borrow.bookid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */

    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.bookid
     *
     * @param bookid the value for borrow.bookid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.readerid
     *
     * @return the value of borrow.readerid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getReaderid() {
        return readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.readerid
     *
     * @param readerid the value for borrow.readerid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setReaderid(String readerid) {
        this.readerid = readerid == null ? null : readerid.trim();
    }
}