package com.liucan.entity;

import java.util.Date;

public class Borrow extends BorrowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.fineid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Integer fineid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.borrowdate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Date borrowdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow.expiredate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Date expiredate;
    private Reader reader;
    private Book book;

    public Reader getReader() {
        return reader;
    }

    public void setReader(Reader reader) {
        this.reader = reader;
    }

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.fineid
     *
     * @return the value of borrow.fineid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Integer getFineid() {
        return fineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.fineid
     *
     * @param fineid the value for borrow.fineid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setFineid(Integer fineid) {
        this.fineid = fineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.borrowdate
     *
     * @return the value of borrow.borrowdate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Date getBorrowdate() {
        return borrowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.borrowdate
     *
     * @param borrowdate the value for borrow.borrowdate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setBorrowdate(Date borrowdate) {
        this.borrowdate = borrowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow.expiredate
     *
     * @return the value of borrow.expiredate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Date getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow.expiredate
     *
     * @param expiredate the value for borrow.expiredate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }
}