package com.liucan.entity;

import java.util.Date;

public class Fine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fine.fineid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Integer fineid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fine.damage
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Double damage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fine.damagemoney
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Double damagemoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fine.overdueday
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Integer overdueday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fine.overduedate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Double overduemoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fine.paymenttype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Byte paymenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fine.paymentmoney
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Double paymentmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fine.fineid
     *
     * @return the value of fine.fineid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Integer getFineid() {
        return fineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fine.fineid
     *
     * @param fineid the value for fine.fineid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setFineid(Integer fineid) {
        this.fineid = fineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fine.damage
     *
     * @return the value of fine.damage
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Double getDamage() {
        return damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fine.damage
     *
     * @param damage the value for fine.damage
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setDamage(Double damage) {
        this.damage = damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fine.damagemoney
     *
     * @return the value of fine.damagemoney
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Double getDamagemoney() {
        return damagemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fine.damagemoney
     *
     * @param damagemoney the value for fine.damagemoney
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setDamagemoney(Double damagemoney) {
        this.damagemoney = damagemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fine.overdueday
     *
     * @return the value of fine.overdueday
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Integer getOverdueday() {
        return overdueday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fine.overdueday
     *
     * @param overdueday the value for fine.overdueday
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setOverdueday(Integer overdueday) {
        this.overdueday = overdueday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fine.overduedate
     *
     * @return the value of fine.overduedate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Double getOverduemoney() {
        return overduemoney;
    }

    public void setOverduemoney(Double overduemoney) {
        this.overduemoney = overduemoney;
    }

    public Byte getPaymenttype() {
        return paymenttype;
    }

    public void setPaymenttype(Byte paymenttype) {
        this.paymenttype = paymenttype;
    }

    public Double getPaymentmoney() {
        return paymentmoney;
    }

    public void setPaymentmoney(Double paymentmoney) {
        this.paymentmoney = paymentmoney;
    }
}