package com.liucan.entity;

import java.util.Date;

public class Reader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.readid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String readid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.readname
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String readname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.sex
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.readertype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String readertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.readertel
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String readertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.qq
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.sfz
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String sfz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.registerdate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Date registerdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.status
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.department
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.readerclass
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String readerclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.readeradress
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    private String readeradress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.readid
     *
     * @return the value of reader.readid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getReadid() {
        return readid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.readid
     *
     * @param readid the value for reader.readid
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setReadid(String readid) {
        this.readid = readid == null ? null : readid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.readname
     *
     * @return the value of reader.readname
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getReadname() {
        return readname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.readname
     *
     * @param readname the value for reader.readname
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setReadname(String readname) {
        this.readname = readname == null ? null : readname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.sex
     *
     * @return the value of reader.sex
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.sex
     *
     * @param sex the value for reader.sex
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.readertype
     *
     * @return the value of reader.readertype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getReadertype() {
        return readertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.readertype
     *
     * @param readertype the value for reader.readertype
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setReadertype(String readertype) {
        this.readertype = readertype == null ? null : readertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.readertel
     *
     * @return the value of reader.readertel
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getReadertel() {
        return readertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.readertel
     *
     * @param readertel the value for reader.readertel
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setReadertel(String readertel) {
        this.readertel = readertel == null ? null : readertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.qq
     *
     * @return the value of reader.qq
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.qq
     *
     * @param qq the value for reader.qq
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.sfz
     *
     * @return the value of reader.sfz
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getSfz() {
        return sfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.sfz
     *
     * @param sfz the value for reader.sfz
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setSfz(String sfz) {
        this.sfz = sfz == null ? null : sfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.registerdate
     *
     * @return the value of reader.registerdate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.registerdate
     *
     * @param registerdate the value for reader.registerdate
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.status
     *
     * @return the value of reader.status
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.status
     *
     * @param status the value for reader.status
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.department
     *
     * @return the value of reader.department
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.department
     *
     * @param department the value for reader.department
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.readerclass
     *
     * @return the value of reader.readerclass
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getReaderclass() {
        return readerclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.readerclass
     *
     * @param readerclass the value for reader.readerclass
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setReaderclass(String readerclass) {
        this.readerclass = readerclass == null ? null : readerclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.readeradress
     *
     * @return the value of reader.readeradress
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getReaderadress() {
        return readeradress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.readeradress
     *
     * @param readeradress the value for reader.readeradress
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setReaderadress(String readeradress) {
        this.readeradress = readeradress == null ? null : readeradress.trim();
    }
}