package com.liucan.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReaderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public ReaderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andReadidIsNull() {
            addCriterion("readid is null");
            return (Criteria) this;
        }

        public Criteria andReadidIsNotNull() {
            addCriterion("readid is not null");
            return (Criteria) this;
        }

        public Criteria andReadidEqualTo(String value) {
            addCriterion("readid =", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidNotEqualTo(String value) {
            addCriterion("readid <>", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidGreaterThan(String value) {
            addCriterion("readid >", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidGreaterThanOrEqualTo(String value) {
            addCriterion("readid >=", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidLessThan(String value) {
            addCriterion("readid <", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidLessThanOrEqualTo(String value) {
            addCriterion("readid <=", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidLike(String value) {
            addCriterion("readid like", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidNotLike(String value) {
            addCriterion("readid not like", value, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidIn(List<String> values) {
            addCriterion("readid in", values, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidNotIn(List<String> values) {
            addCriterion("readid not in", values, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidBetween(String value1, String value2) {
            addCriterion("readid between", value1, value2, "readid");
            return (Criteria) this;
        }

        public Criteria andReadidNotBetween(String value1, String value2) {
            addCriterion("readid not between", value1, value2, "readid");
            return (Criteria) this;
        }

        public Criteria andReadnameIsNull() {
            addCriterion("readname is null");
            return (Criteria) this;
        }

        public Criteria andReadnameIsNotNull() {
            addCriterion("readname is not null");
            return (Criteria) this;
        }

        public Criteria andReadnameEqualTo(String value) {
            addCriterion("readname =", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameNotEqualTo(String value) {
            addCriterion("readname <>", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameGreaterThan(String value) {
            addCriterion("readname >", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameGreaterThanOrEqualTo(String value) {
            addCriterion("readname >=", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameLessThan(String value) {
            addCriterion("readname <", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameLessThanOrEqualTo(String value) {
            addCriterion("readname <=", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameLike(String value) {
            addCriterion("readname like", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameNotLike(String value) {
            addCriterion("readname not like", value, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameIn(List<String> values) {
            addCriterion("readname in", values, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameNotIn(List<String> values) {
            addCriterion("readname not in", values, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameBetween(String value1, String value2) {
            addCriterion("readname between", value1, value2, "readname");
            return (Criteria) this;
        }

        public Criteria andReadnameNotBetween(String value1, String value2) {
            addCriterion("readname not between", value1, value2, "readname");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Byte value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Byte value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Byte value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Byte value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Byte value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Byte value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Byte> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Byte> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Byte value1, Byte value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Byte value1, Byte value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andReadertypeIsNull() {
            addCriterion("readertype is null");
            return (Criteria) this;
        }

        public Criteria andReadertypeIsNotNull() {
            addCriterion("readertype is not null");
            return (Criteria) this;
        }

        public Criteria andReadertypeEqualTo(String value) {
            addCriterion("readertype =", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeNotEqualTo(String value) {
            addCriterion("readertype <>", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeGreaterThan(String value) {
            addCriterion("readertype >", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeGreaterThanOrEqualTo(String value) {
            addCriterion("readertype >=", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeLessThan(String value) {
            addCriterion("readertype <", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeLessThanOrEqualTo(String value) {
            addCriterion("readertype <=", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeLike(String value) {
            addCriterion("readertype like", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeNotLike(String value) {
            addCriterion("readertype not like", value, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeIn(List<String> values) {
            addCriterion("readertype in", values, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeNotIn(List<String> values) {
            addCriterion("readertype not in", values, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeBetween(String value1, String value2) {
            addCriterion("readertype between", value1, value2, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertypeNotBetween(String value1, String value2) {
            addCriterion("readertype not between", value1, value2, "readertype");
            return (Criteria) this;
        }

        public Criteria andReadertelIsNull() {
            addCriterion("readertel is null");
            return (Criteria) this;
        }

        public Criteria andReadertelIsNotNull() {
            addCriterion("readertel is not null");
            return (Criteria) this;
        }

        public Criteria andReadertelEqualTo(String value) {
            addCriterion("readertel =", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelNotEqualTo(String value) {
            addCriterion("readertel <>", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelGreaterThan(String value) {
            addCriterion("readertel >", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelGreaterThanOrEqualTo(String value) {
            addCriterion("readertel >=", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelLessThan(String value) {
            addCriterion("readertel <", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelLessThanOrEqualTo(String value) {
            addCriterion("readertel <=", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelLike(String value) {
            addCriterion("readertel like", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelNotLike(String value) {
            addCriterion("readertel not like", value, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelIn(List<String> values) {
            addCriterion("readertel in", values, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelNotIn(List<String> values) {
            addCriterion("readertel not in", values, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelBetween(String value1, String value2) {
            addCriterion("readertel between", value1, value2, "readertel");
            return (Criteria) this;
        }

        public Criteria andReadertelNotBetween(String value1, String value2) {
            addCriterion("readertel not between", value1, value2, "readertel");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andSfzIsNull() {
            addCriterion("sfz is null");
            return (Criteria) this;
        }

        public Criteria andSfzIsNotNull() {
            addCriterion("sfz is not null");
            return (Criteria) this;
        }

        public Criteria andSfzEqualTo(String value) {
            addCriterion("sfz =", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzNotEqualTo(String value) {
            addCriterion("sfz <>", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzGreaterThan(String value) {
            addCriterion("sfz >", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzGreaterThanOrEqualTo(String value) {
            addCriterion("sfz >=", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzLessThan(String value) {
            addCriterion("sfz <", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzLessThanOrEqualTo(String value) {
            addCriterion("sfz <=", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzLike(String value) {
            addCriterion("sfz like", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzNotLike(String value) {
            addCriterion("sfz not like", value, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzIn(List<String> values) {
            addCriterion("sfz in", values, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzNotIn(List<String> values) {
            addCriterion("sfz not in", values, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzBetween(String value1, String value2) {
            addCriterion("sfz between", value1, value2, "sfz");
            return (Criteria) this;
        }

        public Criteria andSfzNotBetween(String value1, String value2) {
            addCriterion("sfz not between", value1, value2, "sfz");
            return (Criteria) this;
        }

        public Criteria andRegisterdateIsNull() {
            addCriterion("registerdate is null");
            return (Criteria) this;
        }

        public Criteria andRegisterdateIsNotNull() {
            addCriterion("registerdate is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterdateEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate =", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate <>", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateGreaterThan(Date value) {
            addCriterionForJDBCDate("registerdate >", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate >=", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateLessThan(Date value) {
            addCriterionForJDBCDate("registerdate <", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate <=", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateIn(List<Date> values) {
            addCriterionForJDBCDate("registerdate in", values, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("registerdate not in", values, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("registerdate between", value1, value2, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("registerdate not between", value1, value2, "registerdate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andReaderclassIsNull() {
            addCriterion("readerclass is null");
            return (Criteria) this;
        }

        public Criteria andReaderclassIsNotNull() {
            addCriterion("readerclass is not null");
            return (Criteria) this;
        }

        public Criteria andReaderclassEqualTo(String value) {
            addCriterion("readerclass =", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassNotEqualTo(String value) {
            addCriterion("readerclass <>", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassGreaterThan(String value) {
            addCriterion("readerclass >", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassGreaterThanOrEqualTo(String value) {
            addCriterion("readerclass >=", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassLessThan(String value) {
            addCriterion("readerclass <", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassLessThanOrEqualTo(String value) {
            addCriterion("readerclass <=", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassLike(String value) {
            addCriterion("readerclass like", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassNotLike(String value) {
            addCriterion("readerclass not like", value, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassIn(List<String> values) {
            addCriterion("readerclass in", values, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassNotIn(List<String> values) {
            addCriterion("readerclass not in", values, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassBetween(String value1, String value2) {
            addCriterion("readerclass between", value1, value2, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderclassNotBetween(String value1, String value2) {
            addCriterion("readerclass not between", value1, value2, "readerclass");
            return (Criteria) this;
        }

        public Criteria andReaderadressIsNull() {
            addCriterion("readeradress is null");
            return (Criteria) this;
        }

        public Criteria andReaderadressIsNotNull() {
            addCriterion("readeradress is not null");
            return (Criteria) this;
        }

        public Criteria andReaderadressEqualTo(String value) {
            addCriterion("readeradress =", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressNotEqualTo(String value) {
            addCriterion("readeradress <>", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressGreaterThan(String value) {
            addCriterion("readeradress >", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressGreaterThanOrEqualTo(String value) {
            addCriterion("readeradress >=", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressLessThan(String value) {
            addCriterion("readeradress <", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressLessThanOrEqualTo(String value) {
            addCriterion("readeradress <=", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressLike(String value) {
            addCriterion("readeradress like", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressNotLike(String value) {
            addCriterion("readeradress not like", value, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressIn(List<String> values) {
            addCriterion("readeradress in", values, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressNotIn(List<String> values) {
            addCriterion("readeradress not in", values, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressBetween(String value1, String value2) {
            addCriterion("readeradress between", value1, value2, "readeradress");
            return (Criteria) this;
        }

        public Criteria andReaderadressNotBetween(String value1, String value2) {
            addCriterion("readeradress not between", value1, value2, "readeradress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reader
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 29 16:04:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reader
     *
     * @mbg.generated Sun Dec 29 16:04:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}